
title: Yusuf al-Qaradawi Books | كتب و مؤلفات الشيخ العلامة يوسف القرضاوي
url: 'http://qaradawi.net/'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name:  كتب و مؤلفات الشيخ العلامة يوسف القرضاوي 
tagline: Yusuf al-Qaradawi's Books
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
website: qaradawi.net #do not add http://
github: qaradawi


#Update all the sections by editing the files inside _includes folder.
